version: '3.2'

volumes:
  jenkins-home:
    
services:
  jenkins:
    image: jenkins-docker
    build: .
    restart: unless-stopped
    environment:
      - JENKINS_JNLP_URL=<%tbd%>
      - JENKINS_AGENT_SECRET=<%tbd%>
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - jenkins-home:/home/jenkins/agent
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-docker
        

